### ISSUE TITLE
feature request: the bot leaves after a period of inactivity

### ISSUE THREAD

**Issue by abovearth** [MeesCode/mmjs-bot#3]
The bot leaves the voice chat after a period of inactivity, like 5 or 10 minutes, after the queue is finished or empty. That would be a nice addition to the discord bot

**Comment by MeesCode** [comment]
$q has been added, $a(add), $r(emove) and $s(search) will soon follow

**Comment by MeesCode** [comment]
done. It checks every 30 seconds if it is in an empty channel and disconnects accordingly
